setono_sylius_completeness_admin_completeness_rule:
    resource: |
        alias: setono_sylius_completeness.completeness_rule
        section: admin
        permission: true
        except: ['show']
        redirect: update
        grid: setono_sylius_completeness_admin_completeness_rule
        templates: "@SyliusAdmin\\Crud"
        vars:
            all:
                templates:
                    form: "@SetonoSyliusCompletenessPlugin/Admin/CompletenessRule/_form.html.twig"
            index:
                icon: tasks
    type: sylius.resource

setono_sylius_completeness_admin_context_setting:
    resource: |
        alias: setono_sylius_completeness.context_setting
        section: admin
        permission: true
        except: ['show']
        redirect: update
        grid: setono_sylius_completeness_admin_context_setting
        templates: "@SyliusAdmin\\Crud"
        vars:
            all:
                templates:
                    form: "@SetonoSyliusCompletenessPlugin/Admin/ContextSetting/_form.html.twig"
            index:
                icon: sliders horizontal
    type: sylius.resource

setono_sylius_completeness_admin_product_bulk_recalculate:
    path: /products/completeness/bulk-recalculate
    methods: [POST]
    defaults:
        _controller: setono_sylius_completeness.controller.admin.bulk_recalculate

setono_sylius_completeness_admin_product_recalculate:
    path: /products/{id}/completeness/recalculate
    methods: [POST]
    requirements:
        id: \d+
    defaults:
        _controller: setono_sylius_completeness.controller.admin.recalculate_product

setono_sylius_completeness_admin_dashboard:
    path: /completeness/dashboard
    methods: [GET]
    defaults:
        _controller: setono_sylius_completeness.controller.admin.dashboard

setono_sylius_completeness_admin_recalculate_all:
    path: /completeness/recalculate-all
    methods: [POST]
    defaults:
        _controller: setono_sylius_completeness.controller.admin.recalculate_all

setono_sylius_completeness_admin_preview:
    path: /completeness/preview
    methods: [GET]
    defaults:
        _controller: setono_sylius_completeness.controller.admin.preview
